[package]
name = "hackshell"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.40"
readline = { git = "https://github.com/pfrankw/readline.git", version = "0.1.6" }
shlex = "1.3.0"
tokio = { version = "1.44.2", features = ["full"] }
