[package]
name = "hackshell"
version = "0.1.0"
description = "Lightweight, customizable shell framework"
license = "MIT"
edition = "2024"

[dependencies]
futures = "0.3"
async-trait = "0.1.88"
chrono = "0.4.40"
shlex = "1.3.0"
crossterm = { version = "0.29.0", features = ["event-stream"] }
tokio = { version = "1.44.2", features = ["full"] }
clap = { version = "4.5.37", features = ["derive"] }
