[package]
name = "hackshell"
version = "0.1.8"
description = "Lightweight, customizable shell framework"
repository = "https://github.com/pfrankw/hackshell"
license = "MIT"
edition = "2024"

[dependencies]
chrono = "0.4.40"
shlex = "1.3.0"
crossterm = "0.29.0"
clap = { version = "4.5.37", features = ["derive"] }
