[package]
name = "hackshell"
version = "0.1.5"
description = "Lightweight, customizable shell framework"
repository = "https://github.com/pfrankw/hackshell"
license = "MIT"
edition = "2024"

[dependencies]
futures = "0.3"
async-trait = "0.1.88"
chrono = "0.4.40"
shlex = "1.3.0"
crossterm = "0.29.0"
tokio = { version = "1.44.2", features = ["full"] }
clap = { version = "4.5.37", features = ["derive"] }
