[package]
name = "hackshell"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
chrono = "0.4.40"
crossterm = { version = "0.29.0", features = ["event-stream"] }
readline = { git = "https://github.com/pfrankw/readline.git", version = "0.1.7" }
shlex = "1.3.0"
tokio = { version = "1.44.2", features = ["full"] }
futures = "0.3"
futures-timer = "3.0"
clap = { version =  "4.5.37", features = ["derive"] }

[[example]]
name = "helloworld"
path = "src/examples/helloworld.rs"

[[example]]
name = "runtask"
path = "src/examples/runtask.rs"

[[example]]
name = "printsecret"
path = "src/examples/printsecret.rs"

[[example]]
name = "counter"
path = "src/examples/counter.rs"
